spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/veterinary
    username: postgres
    password: whatisbeyond
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      hibernate:
        SQL: debug
